services:
  test-runner:
    build: .
    container_name: java-test-runner
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./allure-results:/shared/allure-results
    working_dir: /app
    environment:
      - TAGS=@Checkout
    command: >
      sh -c "mvn clean test -Dcucumber.filter.tags=${TAGS} && cp -r target/allure-results/* /shared/allure-results/"

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./target/allure-report:/app/allure-report
