name: CI Advantage End2End Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      allure:
        image: frankescobar/allure-docker-service
        ports:
          - 5050:5050
        volumes:
          - /github/workspace/target/allure-results:/app/allure-results

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Install Maven deps
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # 4. Run tests
      - name: Run tests with Maven
        run: mvn clean test

      # 5. Upload allure-results for history/debug
      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # 6. Generate Allure report (CLI way inside GH Action)
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: allure-history

      # 7. Deploy Allure report to GitHub Pages
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report