name: CI Advantage Shopping End2End Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-allure .

      - name: Run tests inside Docker
        run: docker run --rm -e ENV=dev -v ${{ github.workspace }}/target:/app/target playwright-allure

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o target/allure-report
          allure open target/allure-report