name: CI Advantage-Shopping End2End Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      allure:
        image: frankescobar/allure-docker-service
        ports:
          - 5050:5050
        volumes:
          - /github/workspace/target/allure-results:/app/allure-results

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests with Maven
        run: mvn clean test

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: allure-history

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report